In [22]:
print("      ")

In [23]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#### Import the required libraries

In [24]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
print(tf.__version__)

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

2.10.0


##### Samples sentences

In [4]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

print(sent)     

['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']


#### Define the vocabulary size

In [5]:
vocab_size=500

In [6]:
one_hot_repr = [one_hot(word, vocab_size) for word in sent]
one_hot_repr

[[14, 398, 184, 306],
 [14, 398, 184, 162],
 [14, 29, 184, 461],
 [94, 267, 74, 210, 329],
 [94, 267, 74, 210, 204],
 [287, 14, 150, 184, 352],
 [394, 270, 161, 210]]

#### Word embedding representation

In [12]:
### Pre-padding 
# Choose an arbitrary number - little more than the available sentence length
sent_length = 10
padded_docs = pad_sequences(sequences=one_hot_repr, maxlen=sent_length, padding='pre')
padded_docs

array([[  0,   0,   0,   0,   0,   0,  14, 398, 184, 306],
       [  0,   0,   0,   0,   0,   0,  14, 398, 184, 162],
       [  0,   0,   0,   0,   0,   0,  14,  29, 184, 461],
       [  0,   0,   0,   0,   0,  94, 267,  74, 210, 329],
       [  0,   0,   0,   0,   0,  94, 267,  74, 210, 204],
       [  0,   0,   0,   0,   0, 287,  14, 150, 184, 352],
       [  0,   0,   0,   0,   0,   0, 394, 270, 161, 210]], dtype=int32)

In [14]:
### Choose an arbitrary value for dimensions - to represent each word in this dimension
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim, input_length=sent_length))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
padded_docs[0]

array([  0,   0,   0,   0,   0,   0,  14, 398, 184, 306], dtype=int32)

In [20]:
model.predict(padded_docs[0])

1/1 [==============================] - 0s 84ms/step


array([[-0.02178626, -0.04447852, -0.04430599, -0.0412912 , -0.03790152,
         0.04866621,  0.01314322, -0.04784761, -0.04765183,  0.0291011 ],
       [-0.02178626, -0.04447852, -0.04430599, -0.0412912 , -0.03790152,
         0.04866621,  0.01314322, -0.04784761, -0.04765183,  0.0291011 ],
       [-0.02178626, -0.04447852, -0.04430599, -0.0412912 , -0.03790152,
         0.04866621,  0.01314322, -0.04784761, -0.04765183,  0.0291011 ],
       [-0.02178626, -0.04447852, -0.04430599, -0.0412912 , -0.03790152,
         0.04866621,  0.01314322, -0.04784761, -0.04765183,  0.0291011 ],
       [-0.02178626, -0.04447852, -0.04430599, -0.0412912 , -0.03790152,
         0.04866621,  0.01314322, -0.04784761, -0.04765183,  0.0291011 ],
       [-0.02178626, -0.04447852, -0.04430599, -0.0412912 , -0.03790152,
         0.04866621,  0.01314322, -0.04784761, -0.04765183,  0.0291011 ],
       [ 0.02195481,  0.03900411,  0.0042785 ,  0.02788064, -0.04553607,
         0.04562937,  0.0378674 , -0.01217673

#### Example-2

In [21]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

#### One-Hot encoding

In [31]:
vocab_size = 500
one_hot_repr = [one_hot(input_text=doc, n=vocab_size) for doc in sent]
one_hot_repr

[[14, 67, 169, 74, 7, 258],
 [116, 285, 169, 413, 499, 144],
 [94, 474, 452, 363],
 [14, 494, 169, 209, 14, 127],
 [278, 185, 301, 169, 413, 499, 144],
 [454, 169, 413, 499, 163, 89]]

#### Pre-padding

In [34]:
sent_length = 10
padded_docs = pad_sequences(one_hot_repr, maxlen=sent_length, padding='pre')
padded_docs

array([[  0,   0,   0,   0,  14,  67, 169,  74,   7, 258],
       [  0,   0,   0,   0, 116, 285, 169, 413, 499, 144],
       [  0,   0,   0,   0,   0,   0,  94, 474, 452, 363],
       [  0,   0,   0,   0,  14, 494, 169, 209,  14, 127],
       [  0,   0,   0, 278, 185, 301, 169, 413, 499, 144],
       [  0,   0,   0,   0, 454, 169, 413, 499, 163,  89]], dtype=int32)

#### Embedding layer representation

In [36]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=20, input_length=sent_length))
model.compile('adam', 'mse')

In [37]:
padded_docs[0]

array([  0,   0,   0,   0,  14,  67, 169,  74,   7, 258], dtype=int32)

In [40]:
model.predict(padded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  0.02429706, -0.01433082,
         0.02211881, -0.03901112, -0.04952569, -0.01862989,  0.01064403,
        -0.00631316, -0.01467409, -0.00314237, -0.01295899,  0.01379449],
       [-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  0.02429706, -0.01433082,
         0.02211881, -0.03901112, -0.04952569, -0.01862989,  0.01064403,
        -0.00631316, -0.01467409, -0.00314237, -0.01295899,  0.01379449],
       [-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  0.02429706, -0.01433082,
         0.02211881, -0.03901112, -0.04952569, -0.01862989,  0.01064403,
        -0.00631316, -0.01467409, -0.00314237, -0.01295899,  0.01379449],
       [-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  

In [41]:
model.predict(padded_docs[1])

1/1 [==============================] - 0s 22ms/step


array([[-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  0.02429706, -0.01433082,
         0.02211881, -0.03901112, -0.04952569, -0.01862989,  0.01064403,
        -0.00631316, -0.01467409, -0.00314237, -0.01295899,  0.01379449],
       [-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  0.02429706, -0.01433082,
         0.02211881, -0.03901112, -0.04952569, -0.01862989,  0.01064403,
        -0.00631316, -0.01467409, -0.00314237, -0.01295899,  0.01379449],
       [-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  0.02429706, -0.01433082,
         0.02211881, -0.03901112, -0.04952569, -0.01862989,  0.01064403,
        -0.00631316, -0.01467409, -0.00314237, -0.01295899,  0.01379449],
       [-0.0273088 , -0.03328081,  0.02821061,  0.00929148, -0.02727257,
        -0.03545044, -0.03509932, -0.04069757,  